language: node_js

node_js:
  - '6.2'

sudo: false

install:
  - travis_retry npm install

script:
  - npm run lint
  - npm test

env:
  global:
  - secure: B57auj7xBIYsvHnt99AeO4pHOE0gqicrx/nf28yel7jx6tozUWXFzuBsIDILTREFMTPncAn87WOfbBRZ6ug2xduOyyl/VimoBmMNLCTIz0fpTbxisjIlbEbT+GbdkOxbLm6Zs8k24XBBjvCEmRAnXTgWC9jYNweq5C1hkvQBBpnvTenC2trJCsfwMkFQ2oVX0I05+7nm7aEL8enagov1pqGbC2XJfGjZaGRPmSYaftKhHG20Gkj8g7JMCMLZzxp6OF/+f9/LMdByu0dbv2jaYks9aGBWc83EX+DZGz1tLPs7DOzF6iDJcOcse14OI7zDZ7Q9mb5B8B8VHXphmlYBQx+C+J1RgzZvwYs2O4ZfqMUfc6+gRLDWdiYVHGSszbHIBS11PGQdKlSPjF3SFo0U3DsqDj+hR4epPXf5rmiktt/yUJOctphoQzGtav3+a4UX2pVuKgLZn3jeFylcTnQNRMt3lz0cbakQrJDau/ZWcENADdOyrUY2/y1rCpCBy4HqM0HcuNEPxoQ18CLZkSi/Guf3fpOHtloeFnu3+VnirQJcu/HPPODh/8gUVCz8JtxjNQuozdI8TqPo4/2Q66fkRqGA8Ywjj4taymTrtsw9iZQcE5dAW33Ui2zpoFDHZPPpM0Enf5Ys5NiqDXR13vNIEMmFCMi3hFgTESMwYPFy3pQ=
  - secure: iK5i+k1Zn9cOMYI9H58BcJR0zkpNn6msvubRbVCnWjJ7fhWr2gU0jnU6wWbkiZ4d/LtgF/SDgDDnLF/yqC/guax2V3sY+Qu6EEmHYAAfKTCw3CWGLQj/Lx0GX3UpSAOnzXi9D7olvTm2g03UDlv5bRONoddrGCV06D/qcOqOhGchmo3DUj54T4SmJdKVAEcRbnVEzqDSzt+80hUFO+jKL1hdexn1Nmcyzx6u8hl+BxbOUYaVX0pny8OSAwYTMc1TkHfSK/dioVpWH+xS4FzRDmO/7cyjLeaL+/GDOp6zmHgXC7lxGB4a5sS8W2nQZT/xbEPrlZrR4RKqxjBpW2Xhn/zYe47CitKRUM4vPalGCwRjmiNY0MCOGuK7qrbCeHUx37vLh7fckD2N9h+79RWj6RXcr3wcz6OXY9Ek8VvH1P3a4jviPXT3KoRLDXgwER1j7ycobLlVCcVpTScib2d9KWZ1ikyfE3jvo5zcVUhmNUFmrjC+i8YY59iPSW0maj7kV9mKVVkw7aq2UDW/bk23Fd7NA7b14CUc4LERszMB2G1aCpLcgU5khDEPDfFYC7u6sF3eavm/+D3h4L2d7DAua5zTHEQwFpcO4815RtQDnExEUYhfdCPDKKFCbZF/4l4K6PExxzjGzIB/AKmxSJqiJjtt6Lb70s9S6HpWCnjoLJs=
