service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    MyCustomS3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: com.serverless.tests.integration.my.custom.s3.bucket
  Outputs:
    MyCustomOutput:
      Value: SomeValue
      Description: Used to test custom outputs
