service: aws-nodejs

provider: aws

functions:
  hello:
    handler: handler.hello
    events:
      - s3: serverless-integration-test-suite-s3
      - s3:
          bucket: serverless-integration-test-suite-s3
          event: s3:ObjectRemoved:*