service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  apiKeys:
    - myApiKey

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
          integration: lambda
          private: true
